version: "3"

vars:
  HF_HOME: "{{.HOME}}/hf-cache"
  HF_HUB_CACHE: "{{.HF_HOME}}/hub"

tasks:

  hf:ls:
    desc: "キャッシュ一覧（公式）"
    env:
      HF_HOME: "{{.HF_HOME}}"
      HF_HUB_CACHE: "{{.HF_HUB_CACHE}}"
    cmds:
      - uvx hf cache ls --revisions --format table

  hf:prune:
    desc: "不要なキャッシュ削除（公式）"
    env:
      HF_HOME: "{{.HF_HOME}}"
      HF_HUB_CACHE: "{{.HF_HUB_CACHE}}"
    cmds:
      - uvx hf cache prune --dry-run
      - uvx hf cache prune --yes

  hf:scan:
    desc: "旧CLI互換のスキャン"
    env:
      HF_HOME: "{{.HF_HOME}}"
      HF_HUB_CACHE: "{{.HF_HUB_CACHE}}"
    cmds:
      - uv run huggingface-cli scan-cache

  hf:link:
    desc: "共有キャッシュのモデルを models/ に手動リンク"
    vars:
      SRC: "{{.SRC}}"   # 実体（スナップショットパス）
      DST: "{{.DST}}"   # models/ 以下の名前
    cmds:
      - mkdir -p models
      - ln -sf "{{.SRC}}" "models/{{.DST}}"

  hf:clean-links:
    desc: "壊れリンク削除"
    cmds:
      - find models -xtype l -delete