version: "3"

vars:
  HF_HOME: "{{.HOME}}/hf-cache"
  HF_HUB_CACHE: "{{.HF_HOME}}/hub"

tasks:

  hf:ls:
    desc: "キャッシュ一覧（公式 CLI）"
    env:
      HF_HOME: "{{.HF_HOME}}"
      HF_HUB_CACHE: "{{.HF_HUB_CACHE}}"
    cmds:
      - uvx hf cache ls --revisions --format table

  hf:prune:
    desc: "不要なキャッシュの削除（公式 CLI）"
    env:
      HF_HOME: "{{.HF_HOME}}"
      HF_HUB_CACHE: "{{.HF_HUB_CACHE}}"
    cmds:
      - uvx hf cache prune --dry-run
      - uvx hf cache prune --yes

  hf:scan:
    desc: "旧 CLI の互換キャッシュスキャン（scan-cache）"
    env:
      HF_HOME: "{{.HF_HOME}}"
      HF_HUB_CACHE: "{{.HF_HUB_CACHE}}"
    cmds:
      - uv run huggingface-cli scan-cache

  hf:link:
    desc: "共有キャッシュにあるモデルを ./models 内にシンボリックリンクで見える化"
    vars:
      SRC: "{{.SRC}}"  # 実体パス（HF_HUB_CACHE 内の snapshot など）
      DST: "{{.DST}}"  # models/ 配下のリンク名
    cmds:
      - mkdir -p models
      - ln -sf "{{.SRC}}" "models/{{.DST}}"

  hf:clean-links:
    desc: "壊れたシンボリックリンクを削除"
    cmds:
      - find models -xtype l -delete
