version: "3"

vars:
  HF_HOME: '{{ coalesce (env "HF_HOME") (print (env "HOME") "/hf-cache") }}'
  HF_HUB_CACHE: '{{ coalesce (env "HF_HUB_CACHE") (print .HF_HOME "/hub") }}'

tasks:
  hf:env:
    desc: "共通キャッシュの場所を表示"
    cmds:
      - echo "HF_HOME={{.HF_HOME}}"
      - echo "HF_HUB_CACHE={{.HF_HUB_CACHE}}"

  hf:prefetch:
    desc: "モデルを共有 HF_HUB_CACHE にダウンロード（デフォルト: org/model-name）"
    env:
      HF_HOME: '{{.HF_HOME}}'
      HF_HUB_CACHE: '{{.HF_HUB_CACHE}}'
    vars:
      REPO: '{{ default "org/model-name" .REPO }}'
      DEST: '{{ printf "%s/models--%s" .HF_HUB_CACHE (replace .REPO "/" "--") }}'
    cmds:
      - mkdir -p "{{.HF_HUB_CACHE}}"
      - >
        uv run huggingface-cli download {{.REPO}}
        --local-dir "{{.DEST}}"

  hf:scan:
    desc: "キャッシュ状態を表示"
    env:
      HF_HOME: '{{.HF_HOME}}'
      HF_HUB_CACHE: '{{.HF_HUB_CACHE}}'
    cmds:
      - uv run huggingface-cli scan-cache