version: "3"

vars:
  HF_HOME: '{{coalesce (env "HF_HOME") (print (env "HOME") "/hf-cache")}}'
  HF_HUB_CACHE: '{{coalesce (env "HF_HUB_CACHE") (print .HF_HOME "/hub")}}'

tasks:
  hf:prefetch:
    desc: "Prefetch a model into shared HF cache"
    env:
      HF_HOME: '{{.HF_HOME}}'
      HF_HUB_CACHE: '{{.HF_HUB_CACHE}}'
    cmds:
      - mkdir -p "{{.HF_HUB_CACHE}}"
      - >
        uv run huggingface-cli download {{.REPO | default "Tongyi-MAI/Z-Image-Turbo"}}
        --local-dir "{{.HF_HUB_CACHE}}/models--{{.REPO | default "Tongyi-MAI--Z-Image-Turbo" | replace "/" "--"}}"

  hf:scan:
    desc: "Show cache status"
    env:
      HF_HOME: '{{.HF_HOME}}'
      HF_HUB_CACHE: '{{.HF_HUB_CACHE}}'
    cmds:
      - uv run huggingface-cli scan-cache

  hf:clean:
    desc: "Clean unused/duplicate cache"
    env:
      HF_HOME: '{{.HF_HOME}}'
      HF_HUB_CACHE: '{{.HF_HUB_CACHE}}'
    cmds:
      - uv run huggingface-cli delete-cache

  hf:ls:
    desc: "キャッシュ一覧（公式 CLI）"
    env:
      HF_HOME: '{{.HF_HOME}}'
      HF_HUB_CACHE: '{{.HF_HUB_CACHE}}'
    cmds:
      - uvx hf cache ls --revisions --format table

  hf:prune:
    desc: "不要なキャッシュの削除（公式 CLI）"
    env:
      HF_HOME: '{{.HF_HOME}}'
      HF_HUB_CACHE: '{{.HF_HUB_CACHE}}'
    cmds:
      - uvx hf cache prune --dry-run
      - uvx hf cache prune --yes

  hf:link:
    desc: "共有キャッシュにあるモデルを ./models 内にシンボリックリンクで見える化"
    vars:
      SRC: "{{.SRC}}"  # 実体パス（HF_HUB_CACHE 内の snapshot など）
      DST: "{{.DST}}"  # models/ 配下のリンク名
    cmds:
      - mkdir -p models
      - ln -sf "{{.SRC}}" "models/{{.DST}}"

  hf:clean-links:
    desc: "壊れたシンボリックリンクを削除"
    cmds:
      - find models -xtype l -delete

  hf:auto-link:
    desc: "models.yaml に基づいてモデルを自動リンク"
    vars:
      CONFIG: "models.yaml"
    cmds:
      - mkdir -p models
      - |
        python3 <<'EOF'
        import os, yaml, subprocess, json, pathlib

        HF_CACHE = os.path.expandvars("$HF_HUB_CACHE")

        with open("models.yaml") as f:
            config = yaml.safe_load(f)

        for m in config.get("models", []):
            org = m["org"]
            repo = m["repo"]
            hub_dir = f"models--{org}--{repo}"
            hub_path = pathlib.Path(HF_CACHE) / hub_dir / "snapshots"

            if not hub_path.exists():
                print(f"[skip] not downloaded: {org}/{repo}")
                continue

            # 最新snapshotを一つ選ぶ
            snapshots = sorted(hub_path.iterdir(), key=lambda p: p.stat().st_mtime, reverse=True)
            if not snapshots:
                print(f"[skip] no snapshots: {org}/{repo}")
                continue

            snap = snapshots[0]  # 最新
            dst = pathlib.Path("models") / repo

            # symlink 作成
            if dst.exists() or dst.is_symlink():
                dst.unlink()

            dst.symlink_to(snap, target_is_directory=True)
            print(f"[link] {repo} -> {snap}")
        EOF

  hf:auto-download:
    desc: "models.yaml に基づいて必要モデルをすべてダウンロード"
    cmds:
      - |
        python3 <<'EOF'
        import os, yaml, subprocess

        with open("models.yaml") as f:
            config = yaml.safe_load(f)

        for m in config.get("models", []):
            org = m["org"]
            repo = m["repo"]
            model = f"{org}/{repo}"
            print(f"[download] {model}")
            subprocess.run(["uvx", "hf", "download", model], check=False)
        EOF

  hf:sync:
    desc: "models.yaml → 自動ダウンロード → 自動リンク（フル同期）"
    cmds:
      - task: hf:auto-download
      - task: hf:auto-link